### ISSUE TITLE
mapping : reference a resource like '/store/products' instead of /products

### ISSUE THREAD

**Issue by biancamullie** [dimitrydhondt/sri4node#80] opened 2015-11-09 14:31 UTC
```
package: {references: '/packages'} works fine but i need 
package: {references: '/store/packages'}
```

and this gives an error like this :+1: 
GET processing had errors. Removing pg client from pool. Error : 
TypeError: Cannot read property 'type' of undefined
    at module.exports.mapColumnsToObject (/home/bianca/workspace/store-api/node_modules/sri4node/js/common.js:69:48)
    at /home/bianca/workspace/store-api/node_modules/sri4node/sri4node.js:795:11
    at _fulfilled (/home/bianca/workspace/store-api/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/bianca/workspace/store-api/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/bianca/workspace/store-api/node_modules/q/q.js:796:13)
    at /home/bianca/workspace/store-api/node_modules/q/q.js:604:44
    at runSingle (/home/bianca/workspace/store-api/node_modules/q/q.js:137:13)
    at flush (/home/bianca/workspace/store-api/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by eznibe** [comment] 2015-12-02 21:32
Currently it is failing because it's checking that the defined 'references' is one of the configured resources and in this case '/store/packages' is not a resource ('/packages' is)

@dimitrydhondt it is ok if I remove that check allowing to define the 'references' as the client wants?

**Comment by dimitrydhondt** [comment] 2015-12-03 14:19
The idea is to allow /x/y/../guid for resources.
Currently we only allow /x/guid.

Does that clear things up ?

**Comment by eznibe** [comment] 2015-12-03 15:11
not clear yet, sorry..
this means that the change is not only for the 'references' map but also to allow to configure resources with type /x/y/.. ? that part it's not clear, why you would want to do that?

**Comment by dimitrydhondt** [comment] 2015-12-03 18:09
Because Bianca a is building an API that has resources like /store/packages, /store/products, etc...

When running locally it is necessary to run the exact links. It is not enough to map /store in NGINX on test/acc/prod.

Besides this JSONB columns store full the full relative URLs (/store/products/{guid})

**Comment by dimitrydhondt** [comment] 2015-12-24 12:20
Hej @eznibe, is this issue closed now ?

**Comment by eznibe** [comment] 2015-12-24 16:47
It is closed but pushed in the branch 'extendtype-80'. I need to merge it to master, I was waiting for some review there but maybe it's better if I do the merge, I added many tests and all seems to work fine.

**Comment by dimitrydhondt** [comment] 2015-12-24 21:33
Ok. Please merge :)

**Comment by rodrigouroz** [comment] 2016-05-11 11:09
Hi @eznibe, is there any chance you can merge this? or help me do it since you did the change?

I'm closing as many issues as possible.

**Comment by dimitrydhondt** [comment] 2016-05-12 07:16
I think the merge allready happened. @eznibe ?
Please double check, ok ?

@biancamullie Can you confirm that it is working ? I remember it was for Store API that we needed it first.

**Comment by rodrigouroz** [comment] 2016-08-26 18:54
Merge done, confirmed by @eznibe

**Comment by feelitloveit** [comment] 2017-03-16 10:20
Not all functionalities are working.. I am investigating this.

**Closed** 2017-03-16 13:44 UTC
Labels: feature
